name: Deploy Documentation 

on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt-get install doxygen -y

    - name: Generate Doxygen Documentation
      run: doxygen

  deploy:
    needs: generate
    runs-on: ubuntu-latest

    steps:
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3 
        with:
          path: Pipeline/html
